# Generated by Django 4.1.2 on 2022-10-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecsvmodel',
            name='filename',
        ),
    ]
